AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Data QC Pipeline (S3 -> Lambda -> reports/ prefix)

Parameters:
  InputBucketName:
    Type: String
    Description: "Name of the existing S3 bucket used as input"

Globals:
  Function:
    Runtime: python3.10
    Timeout: 30
    MemorySize: 256

Resources:

  DataQcLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub data-qc-lambda-${AWS::StackName}
      Handler: src.handler.handler
      Runtime: python3.10
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          BUCKET_NAME: !Ref InputBucketName
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:ListBucket
              Resource:
                - !Sub arn:aws:s3:::${InputBucketName}
                - !Sub arn:aws:s3:::${InputBucketName}/*

Outputs:
  DataQcLambdaArn:
    Description: "ARN of the Data QC Lambda"
    Value: !GetAtt DataQcLambda.Arn
  DataQcLambdaName:
    Description: "Name of the Data QC Lambda"
    Value: !Ref DataQcLambda
