# project-05-ml-inference-api - placeholder SAM / infra template
# Replace with project-specific resources (Lambda, S3, DynamoDB, SQS, etc.)
AWSTemplateFormatVersion: '2010-09-09'
Description: "project-05-ml-inference-api infra - replace with real template"
Resources: {}
